CI: pin rust version to 1.79.0
Stable release 1.80.0 has a regression causing compilation errors:

  error[E0282]: type annotations needed for `Box<_>`

Pin stable version to 1.79.0, since we don't need anything later than
our MSRV anyway.

Signed-off-by: Manos Pitsidianakis <manos@pitsidianak.is>